#!/bin/sh
# Pre-commit hook to require tests to pass

echo "Running tests..."
go test ./...
if [ $? -ne 0 ]; then
    echo "Tests failed. Commit aborted."
    exit 1
fi

echo "Building..."
go build -v -o /dev/null ./cmd/clio
if [ $? -ne 0 ]; then
    echo "Build failed. Commit aborted."
    exit 1
fi

echo "Tests and Build passed."
exit 0
