package setup

import (
	"os"
	"path/filepath"
)

// CreateVimConfig creates a sensible Vim configuration for use as a lightweight IDE
func CreateVimConfig() error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}

	vimrcPath := filepath.Join(home, ".vimrc")

	// Check if .vimrc already exists and has content
	if info, err := os.Stat(vimrcPath); err == nil && info.Size() > 100 {
		// Backup existing config
		backupPath := vimrcPath + ".backup"
		if _, err := os.Stat(backupPath); err != nil {
			if err := os.Rename(vimrcPath, backupPath); err == nil {
				os.WriteFile(vimrcPath+".backup.note",
					[]byte("Your original .vimrc was backed up by Clio setup"), 0644)
			}
		}
	}

	vimrc := getVimConfig()
	return os.WriteFile(vimrcPath, []byte(vimrc), 0644)
}

func getVimConfig() string {
	return `" ============================================================================
" Vim Configuration - Lightweight IDE Setup
" Generated by Clio - Termux Setup
" ============================================================================

" Basic Settings
set nocompatible
filetype plugin indent on
syntax on

" UI & Display
set number
set relativenumber
set cursorline
set showmatch
set wildmenu
set wildmode=longest:full,full
set laststatus=2
set ruler
set showcmd
set title
set scrolloff=5

" Colors & Themes
set background=dark
colorscheme desert

" Indentation & Tabs
set autoindent
set smartindent
set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4
set smarttab

" Search Settings
set incsearch
set hlsearch
set ignorecase
set smartcase

" Performance & Behavior
set hidden
set history=1000
set undolevels=1000
set backspace=indent,eol,start
set encoding=utf-8
set fileencoding=utf-8
set mouse=a
set clipboard=unnamedplus
set autoread
set lazyredraw

" File Management
set nobackup
set nowritebackup
set noswapfile
if has('persistent_undo')
  set undodir=~/.vim/undodir
  set undofile
  if !isdirectory(expand('~/.vim/undodir'))
    call mkdir(expand('~/.vim/undodir'), 'p')
  endif
endif

" Split Windows
set splitbelow
set splitright

" Status Line
set statusline=%F
set statusline+=%m
set statusline+=%r
set statusline+=%=
set statusline+=%y
set statusline+=\ [%l/%L]
set statusline+=\ [%c]

" Key Mappings
let mapleader = ","

" Quick save and quit
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>

" Clear search highlight
nnoremap <leader><space> :nohlsearch<CR>

" Better window navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Split windows
nnoremap <leader>v :vsplit<CR>
nnoremap <leader>h :split<CR>

" Buffer navigation
nnoremap <leader>n :bnext<CR>
nnoremap <leader>p :bprevious<CR>
nnoremap <leader>d :bdelete<CR>

" Toggle line numbers
nnoremap <leader>l :set number!<CR>
nnoremap <leader>r :set relativenumber!<CR>

" Indent/unindent in visual mode
vnoremap < <gv
vnoremap > >gv

" Move lines up/down
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" File Explorer (Netrw)
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_winsize = 25
nnoremap <leader>e :Lexplore<CR>

" Auto Commands
autocmd BufWritePre * :%s/\s\+$//e

autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal! g'\"" |
  \ endif

" Language-Specific Settings
autocmd FileType python setlocal shiftwidth=4 tabstop=4 softtabstop=4
autocmd FileType javascript,typescript,json setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType html,css,scss setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType go setlocal noexpandtab shiftwidth=4 tabstop=4
autocmd FileType php setlocal shiftwidth=4 tabstop=4 softtabstop=4
autocmd FileType yaml setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType markdown setlocal wrap linebreak textwidth=80

" Simple Code Completion
set omnifunc=syntaxcomplete#Complete
set completeopt=menuone,longest,preview
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" ============================================================================
" End of Configuration
" ============================================================================
`
}
